### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by AminBlg** [ray-pH/polybar-cava#4]
it uses more cpu than just running cava from the terminal, is there a reason or a fix?

**Comment by ray-pH** [comment]
when you run `cava.sh` directly in the terminal (not from polybar), does the cpu usage also high?

**Comment by ray-pH** [comment]
also, is it abnormally high?

i guess it's expected to use a little bit more cpu since other than running CAVA, it needs to write and read to/from a pipe and also running `sed` to convert the output to unicode charaters (the bars)

**Comment by AminBlg** [comment]
it is not abnormally high, just bit more than usual. But i understand now why it higher
