### ISSUE TITLE
Waybar support

### ISSUE THREAD

**Issue by Theraa0** [ray-pH/polybar-cava#5]
Hej,
just wanted to let you know that this script also works flawlessly with waybar on my system, so the name of this project might be a bit missleading. Maybe you could change it or at least the README file to indicate that.

**Comment by ray-pH** [comment]
I guess that's right. Since `cava.sh` is just outputting unicode characters, any app that can display that will be able to use the script.
I don't know what to change the name into. Maybe adding a small section in the README will do for me.
